/**
 * Download the report's faces into public/fonts, once.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Self-hosted rather than next/font, and fetched one weight at a time. Both
 * halves of that were learned by watching three of the four grounds print in
 * Times New Roman while every browser-side check said the right face was
 * loaded, resolved and painting.
 *
 * The cause is that Google serves a *variable* file whenever a request covers
 * more than one weight of a family that has a variable version, and Chrome
 * cannot embed variable outlines in a PDF — it silently substitutes. The tell is
 * that two weights come back byte-identical in size. Spectral and Marcellus
 * always worked because neither has a variable version to serve.
 *
 * So every weight and style is requested on its own, which yields a static
 * instance. Thirty families were checked this way and all thirty embedded.
 *
 * latin-ext is kept alongside latin because that is where the Sanskrit
 * transliteration lives: the macron of Navāṁśa and the dotted letters of Rāśi
 * and Nakṣatra are all outside basic latin.
 */
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';

const OUT = 'public/fonts';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

/** family -> [weight, style] pairs the report actually uses. */
const WANTED = {
  Spectral: [[400, 'normal'], [400, 'italic'], [600, 'normal']],
  'EB Garamond': [[400, 'normal'], [400, 'italic'], [500, 'normal']],
  'Libre Baskerville': [[400, 'normal'], [400, 'italic'], [700, 'normal']],
  Marcellus: [[400, 'normal']],
  'Cormorant Garamond': [[400, 'normal'], [400, 'italic'], [600, 'normal']],
  Inter: [[400, 'normal'], [600, 'normal']],
};

const slug = (f) => f.toLowerCase().replace(/[^a-z0-9]+/g, '-');
const sizes = new Map();

mkdirSync(OUT, { recursive: true });
const faces = [];

for (const [family, wanted] of Object.entries(WANTED)) {
  for (const [weight, style] of wanted) {
    const spec = style === 'italic' ? `ital,wght@1,${weight}` : `ital,wght@0,${weight}`;
    const url =
      'https://fonts.googleapis.com/css2?family=' +
      family.replace(/ /g, '+') + ':' + spec + '&display=block';
    const css = await (await fetch(url, { headers: { 'user-agent': UA } })).text();

    for (const block of css.match(/\/\*[^*]*\*\/\s*@font-face\s*\{[^}]*\}/g) || []) {
      const subset = (block.match(/\/\*\s*([a-z-]+)\s*\*\//) || [])[1];
      if (subset !== 'latin' && subset !== 'latin-ext') continue;
      const src = (block.match(/url\((https:[^)]+)\)/) || [])[1];
      const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim();
      if (!src) continue;

      const file = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
      if (!existsSync(`${OUT}/${file}`)) {
        const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
        writeFileSync(`${OUT}/${file}`, buf);
        sizes.set(file, buf.length);
      }
      faces.push({ family, file, weight, style, range });
    }
  }
}

// A variable file served for two weights comes back the same size twice. If that
// ever happens again this says so rather than leaving it to be found in a PDF.
const byFamilySubset = new Map();
for (const f of faces) {
  if (f.style !== 'normal') continue;
  const key = `${f.family}|${f.file.split('-').pop()}`;
  const size = sizes.get(f.file);
  if (!size) continue;
  const seen = byFamilySubset.get(key);
  if (seen && seen.size === size) {
    console.warn(`WARNING ${f.family}: ${seen.weight} and ${f.weight} are the same size ` +
      `(${size}B). That is what a variable file looks like, and Chrome will not embed it.`);
  }
  byFamilySubset.set(key, { weight: f.weight, size });
}

const css = faces
  .map(
    (f) =>
      `@font-face {\n  font-family: '${f.family}';\n  font-style: ${f.style};\n` +
      `  font-weight: ${f.weight};\n  font-display: block;\n` +
      `  src: url('/fonts/${f.file}') format('woff2');\n` +
      (f.range ? `  unicode-range: ${f.range};\n` : '') +
      '}',
  )
  .join('\n');

writeFileSync(
  'src/lib/report/fontFace.ts',
  '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n' +
    "/** The report's faces, self-hosted. See the script for why. */\n" +
    'export const REPORT_FONT_FACE = String.raw`\n' + css + '\n`;\n',
);
console.log('wrote src/lib/report/fontFace.ts with', faces.length, 'faces');
